{{- if and .Values.env.db.createSecret (not .Values.env.db.existingSecret) .Values.env.db.dsn }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noppflow.fullname" . }}-db
  labels:
    {{- include "noppflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.env.db.secretKey }}: {{ .Values.env.db.dsn | quote }}
{{- end }}
